---
apiVersion: v1
kind: Service
metadata:
  name: mutateme
  namespace: default
  labels:
    app: mutateme
spec:
  publishNotReadyAddresses: true
  ports:
    - port: 443
      targetPort: 8443
  selector:
    app: mutateme

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mutateme
  namespace: default
  labels:
    app: mutateme
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mutateme
  template:
    metadata:
      name: mutateme
      labels:
        app: mutateme
    spec:
      containers:
        - name: mutator
          image: mariolet/k8s-mutate-webhook:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 250m
              memory: 64Mi

---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: mutateme
  namespace: default
  labels:
    app: mutateme
webhooks:
  - name: mutateme.default.svc.cluster.local
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwdGFXNXAKYTNWaVpVTkJNQjRYRFRFNU1URXdOakUxTkRnek9Wb1hEVEk1TVRFd05ERTFORGd6T1Zvd0ZURVRNQkVHQTFVRQpBeE1LYldsdWFXdDFZbVZEUVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBT1kxClB6NWxFWHVPdmZTRmN5NFBBQyt6bTQ5WWx6cDZzeGZUR2FJbWx3R2tLZ3c2M2IyRFJPQU1MS2J5M1ZUZHF3OG8KQmppNTQybWtNd29JZ05hZXJuVlluVjFsMlQwZVlzTEhEaG5ZZlJaTllnSHFwOEdDS2cxZTE5MDJPUXowY0x3Mgp5Tm5PNFZFS2M1S0I0NFFsVWhjWUtCSHRyY2hzQmJqYXBiM09mWXA2SFNYdzlweUlONDBNWGkyUi9mSEc0L2l1ClU1NFpFb0RZcEJwRnMvUkl5cWd2WG5WMEIyd2xuQVErVXE2SlQ2WElyQnlWMFNtcjZ5NVhsemNtdVU0MTRhbVkKZmdKMkZrTFd0bC8yOS9yeXQ2blAxNW16RFBMMG1CY080RjhWdldpdCtRVlhUUDFhZEptU0lWK1M5bnhIRlNsZQo0TG54SlBrSFJDeVVSUVhUNHkwQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWRKUVFXCk1CUUdDQ3NHQVFVRkJ3TUNCZ2dyQmdFRkJRY0RBVEFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFDM1paREgrcjZ3blZSUFNJTzV6eFQ5TCttc3MrdXoyRk9wU3B4ZkJ2WkI5RDZzdm45Rgoxd0YxVHFpK09PMElzMkYyclBwQUZrYllmMWV4MWVnWVJaMG9nZ3V4UW5WcHZ4dzhCbXk1czBvWGI2YzJ4eUFFCllqWHNnajl0b0dVM2lKTlF1c2ZYamtSdHJIakw3dGNUK2tqQlZpaStyVy9NaEp1bnIrdTFRSi9YNWpVSUoyamoKVlp3NmZzenNLRFd1TGo2dnhkNU1lbUp1Wm1aa3NHMmdEbUZ5YTg1NjN1c1NUOW1IYjRIZEtleERtM0xONW15UQoxTTRUelR0NWNvL2hieUFsS0xTZ2c1KzAvVjlnc0NLSTcvTTdTN1A0bDU2cUJwd0ZMQ3JrUytodms3TitXTHF1CitjTUVjcjlNUDBPM3gvZm8yVnROcGNlbU5qbysrSEpOZ2srZgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      service:
        name: mutateme
        namespace: default
        path: "/mutate"
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["workspaces"]
    namespaceSelector:
      matchLabels:
        mutateme: enabled

---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: mutateme
  namespace: default
  labels:
    app: mutateme
webhooks:
  - name: mutateme.default.svc.cluster.local
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwdGFXNXAKYTNWaVpVTkJNQjRYRFRFNU1URXdOakUxTkRnek9Wb1hEVEk1TVRFd05ERTFORGd6T1Zvd0ZURVRNQkVHQTFVRQpBeE1LYldsdWFXdDFZbVZEUVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBT1kxClB6NWxFWHVPdmZTRmN5NFBBQyt6bTQ5WWx6cDZzeGZUR2FJbWx3R2tLZ3c2M2IyRFJPQU1MS2J5M1ZUZHF3OG8KQmppNTQybWtNd29JZ05hZXJuVlluVjFsMlQwZVlzTEhEaG5ZZlJaTllnSHFwOEdDS2cxZTE5MDJPUXowY0x3Mgp5Tm5PNFZFS2M1S0I0NFFsVWhjWUtCSHRyY2hzQmJqYXBiM09mWXA2SFNYdzlweUlONDBNWGkyUi9mSEc0L2l1ClU1NFpFb0RZcEJwRnMvUkl5cWd2WG5WMEIyd2xuQVErVXE2SlQ2WElyQnlWMFNtcjZ5NVhsemNtdVU0MTRhbVkKZmdKMkZrTFd0bC8yOS9yeXQ2blAxNW16RFBMMG1CY080RjhWdldpdCtRVlhUUDFhZEptU0lWK1M5bnhIRlNsZQo0TG54SlBrSFJDeVVSUVhUNHkwQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWRKUVFXCk1CUUdDQ3NHQVFVRkJ3TUNCZ2dyQmdFRkJRY0RBVEFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFDM1paREgrcjZ3blZSUFNJTzV6eFQ5TCttc3MrdXoyRk9wU3B4ZkJ2WkI5RDZzdm45Rgoxd0YxVHFpK09PMElzMkYyclBwQUZrYllmMWV4MWVnWVJaMG9nZ3V4UW5WcHZ4dzhCbXk1czBvWGI2YzJ4eUFFCllqWHNnajl0b0dVM2lKTlF1c2ZYamtSdHJIakw3dGNUK2tqQlZpaStyVy9NaEp1bnIrdTFRSi9YNWpVSUoyamoKVlp3NmZzenNLRFd1TGo2dnhkNU1lbUp1Wm1aa3NHMmdEbUZ5YTg1NjN1c1NUOW1IYjRIZEtleERtM0xONW15UQoxTTRUelR0NWNvL2hieUFsS0xTZ2c1KzAvVjlnc0NLSTcvTTdTN1A0bDU2cUJwd0ZMQ3JrUytodms3TitXTHF1CitjTUVjcjlNUDBPM3gvZm8yVnROcGNlbU5qbysrSEpOZ2srZgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      service:
        name: mutateme
        namespace: default
        path: "/validate"
    rules:
      - operations: ["CONNECT"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods/exec"]
    sideEffects: None
    admissionReviewVersions: ["v1", "v1beta1"]
    timeoutSeconds: 5
    namespaceSelector:
      matchLabels:
        validateme: enabled
